import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "./components/Navigation";
import Locomotive from "./components/Locomotive";
import GsapScrollTrigger from "./components/GsapScrollTrigger";

const myFont = localFont({ src: "../../public/SaansTRIAL-Regular.ttf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Locomotive />
        <GsapScrollTrigger />
        <Navigation />
        <main className="w-full h-full pt-20">{children}</main>
      </body>
    </html>
  );
}
